name: mistos
dependencies:
  - python=3.8
  - pip
  - pandas
  - scikit-learn
  - scipy=1.4.1
  - sqlite
  - tensorflow
  - pip:
    - aiofiles
    - czifile
    - fastapi
    - matplotlib
    - napari
    - openpyxl
    - pydantic
    - python-bioformats
    - python-javabridge
    - python-multipart
    - scikit-image
    - simpleitk
    - sqlalchemy==1.4.0b2
    - stardist
    - tifffile
    - tqdm
    - uvicorn
    - vispy
    - webencodings
    - xtiff
    - zarr
    - pyqt5
    - auto-tqdm
    # - h5py==2.10.0
    # - numpy==1.16.0
    # - gast